// This file is automatically generated by qtc from "admin.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line admin\admin.qtpl:1
package admin

//line admin\admin.qtpl:1
import (
	FCTypes "github.com/snowheat/falconism/types"
)

//line admin\admin.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line admin\admin.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line admin\admin.qtpl:6
type Page interface {
	//line admin\admin.qtpl:6
	Title() string
	//line admin\admin.qtpl:6
	StreamTitle(qw422016 *qt422016.Writer)
	//line admin\admin.qtpl:6
	WriteTitle(qq422016 qtio422016.Writer)
	//line admin\admin.qtpl:6
	Body() string
	//line admin\admin.qtpl:6
	StreamBody(qw422016 *qt422016.Writer)
	//line admin\admin.qtpl:6
	WriteBody(qq422016 qtio422016.Writer)
//line admin\admin.qtpl:6
}

//line admin\admin.qtpl:12
func StreamPageTemplate(qw422016 *qt422016.Writer, posts []FCTypes.BlogPost) {
	//line admin\admin.qtpl:12
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en-us">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title></title>
	</head>
	<body>
		<h1>Tulis</h1>
		<form action="/admin/post" method="post">
		  	Title:<br>
		  	<input type="text" name="title"><br>
		  	Content:<br>
		  	<textarea name="content"></textarea><br>
			<input type="submit" value="Post">
		</form> 
		<h1>Tulisan</h1>
		`)
	//line admin\admin.qtpl:29
	for _, post := range posts {
		//line admin\admin.qtpl:29
		qw422016.N().S(`
			<h2>`)
		//line admin\admin.qtpl:30
		qw422016.E().S(post.Title)
		//line admin\admin.qtpl:30
		qw422016.N().S(`</h2>
			<p>`)
		//line admin\admin.qtpl:31
		qw422016.E().S(post.Content)
		//line admin\admin.qtpl:31
		qw422016.N().S(`</p>
		`)
		//line admin\admin.qtpl:32
	}
	//line admin\admin.qtpl:32
	qw422016.N().S(`
	</body>
</html>
`)
//line admin\admin.qtpl:35
}

//line admin\admin.qtpl:35
func WritePageTemplate(qq422016 qtio422016.Writer, posts []FCTypes.BlogPost) {
	//line admin\admin.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line admin\admin.qtpl:35
	StreamPageTemplate(qw422016, posts)
	//line admin\admin.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line admin\admin.qtpl:35
}

//line admin\admin.qtpl:35
func PageTemplate(posts []FCTypes.BlogPost) string {
	//line admin\admin.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
	//line admin\admin.qtpl:35
	WritePageTemplate(qb422016, posts)
	//line admin\admin.qtpl:35
	qs422016 := string(qb422016.B)
	//line admin\admin.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
	//line admin\admin.qtpl:35
	return qs422016
//line admin\admin.qtpl:35
}
